# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               RNA-seq Analisys Course
tagline:             Training on Rnaseq Data approach
description:         NGS training
url:                 'https://bioinfo-dirty-jobs.github.io/rana2/'
baseurl:             '/rana2/'
twitter_username:
github_username:  bioinfo-dirty-jobs
pages_url: https://bioinfo-dirty-jobs.github.io/rana2
github_url: https://bioinfo-dirty-jobs.github.io/rana2

# Custom vars
version:             4.0

# Build settings
markdown: kramdown
