# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               RNA-seq Analisys Course
tagline:             Training on  Trascriptomics
description:         NGS training
url:                 'https://bioinfo-dirty-jobs.github.io/rna2020'
baseurl:             '/rna2020/'
twitter_username:
github_username:  bioinfo-dirty-jobs
pages_url: https://bioinfo-dirty-jobs.github.io/rna2020
github_url: https://bioinfo-dirty-jobs.github.io/rna2020

# Custom vars
version:             4.0

# Build settings
markdown: kramdown
